### ISSUE TITLE
Impersonation example for Linux

### ISSUE THREAD

**Issue by lxwang42** [Nisitay/pyp0f#4]
Hello!
would you mind to add an impersonation example for Linux?

**Comment by Nisitay** [comment]
Hey :)

If you're on Linux, you should be able to use any library that can alter packets on the fly (for example: [NetFilterQueue](https://github.com/oremanj/python-netfilterqueue)).

I will attempt to implement it myself and update the examples accordingly.

**Comment by Nisitay** [comment]
Sorry for the late response, I haven't had much time lately to test this myself.
Thankfully, @momo286 added an example for linux impersonation in [this](https://github.com/Nisitay/pyp0f/pull/5) PR.
Let me know if you have any questions!
